import express from 'express';
import { getNotifications, markRead, markAllRead, deleteNotification } from '../controllers/notification.controller.js';
import { protect } from '../middleware/auth.middleware.js';
const router = express.Router();
router.use(protect);
router.get('/', getNotifications);
router.put('/mark-all-read', markAllRead);
router.put('/:id/read', markRead);
router.delete('/:id', deleteNotification);
export default router;
