import express from 'express';
import { getTickets, getTicket, createTicket, updateTicket, replyTicket } from '../controllers/ticket.controller.js';
import { protect, authorize } from '../middleware/auth.middleware.js';
const router = express.Router();
router.use(protect);
router.get('/', getTickets);
router.get('/:id', getTicket);
router.post('/', createTicket);
router.put('/:id', authorize('superAdmin', 'manager'), updateTicket);
router.post('/:id/reply', replyTicket);
export default router;
