// =============================================
// PROJECT CATEGORY DEFINITIONS & METADATA
// =============================================

import {
  Globe,
  Layout,
  Share2,
  Search,
  Target,
  Sparkles,
  Palette,
  Video,
  Smartphone,
  ShoppingBag,
  Rocket,
  Wrench,
  FileText,
  FolderKanban,
} from 'lucide-react';

export const PROJECT_CATEGORIES = {
  web_development: {
    key: 'web_development',
    label: 'Website / Web Dev',
    shortLabel: 'Web Dev',
    icon: Globe,
    color: 'blue',
    badgeClass: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20',
    dotClass: 'bg-blue-500',
    group: 'Engineering',
  },
  web_design: {
    key: 'web_design',
    label: 'Web Design / UI-UX',
    shortLabel: 'Web Design',
    icon: Layout,
    color: 'cyan',
    badgeClass: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20',
    dotClass: 'bg-cyan-500',
    group: 'Design',
  },
  social_media: {
    key: 'social_media',
    label: 'Social Media Marketing',
    shortLabel: 'Social Media',
    icon: Share2,
    color: 'pink',
    badgeClass: 'bg-pink-500/10 text-pink-600 dark:text-pink-400 border-pink-500/20',
    dotClass: 'bg-pink-500',
    group: 'Marketing',
  },
  seo: {
    key: 'seo',
    label: 'SEO & Search Marketing',
    shortLabel: 'SEO',
    icon: Search,
    color: 'emerald',
    badgeClass: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20',
    dotClass: 'bg-emerald-500',
    group: 'Marketing',
  },
  paid_ads: {
    key: 'paid_ads',
    label: 'Paid Ads / Performance',
    shortLabel: 'Paid Ads',
    icon: Target,
    color: 'amber',
    badgeClass: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20',
    dotClass: 'bg-amber-500',
    group: 'Marketing',
  },
  branding: {
    key: 'branding',
    label: 'Branding & Identity',
    shortLabel: 'Branding',
    icon: Sparkles,
    color: 'purple',
    badgeClass: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20',
    dotClass: 'bg-purple-500',
    group: 'Design',
  },
  graphic_design: {
    key: 'graphic_design',
    label: 'Graphic Design',
    shortLabel: 'Graphics',
    icon: Palette,
    color: 'violet',
    badgeClass: 'bg-violet-500/10 text-violet-600 dark:text-violet-400 border-violet-500/20',
    dotClass: 'bg-violet-500',
    group: 'Design',
  },
  video_content: {
    key: 'video_content',
    label: 'Video Production & Content',
    shortLabel: 'Video',
    icon: Video,
    color: 'rose',
    badgeClass: 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20',
    dotClass: 'bg-rose-500',
    group: 'Media',
  },
  video: {
    key: 'video',
    label: 'Video Production',
    shortLabel: 'Video',
    icon: Video,
    color: 'rose',
    badgeClass: 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20',
    dotClass: 'bg-rose-500',
    group: 'Media',
  },
  mobile_app: {
    key: 'mobile_app',
    label: 'Mobile App Development',
    shortLabel: 'Mobile App',
    icon: Smartphone,
    color: 'teal',
    badgeClass: 'bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-500/20',
    dotClass: 'bg-teal-500',
    group: 'Engineering',
  },
  e_commerce: {
    key: 'e_commerce',
    label: 'E-Commerce Solutions',
    shortLabel: 'E-Commerce',
    icon: ShoppingBag,
    color: 'orange',
    badgeClass: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20',
    dotClass: 'bg-orange-500',
    group: 'Engineering',
  },
  saas_product: {
    key: 'saas_product',
    label: 'SaaS Product / Platform',
    shortLabel: 'SaaS',
    icon: Rocket,
    color: 'indigo',
    badgeClass: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20',
    dotClass: 'bg-indigo-500',
    group: 'Product',
  },
  saas: {
    key: 'saas',
    label: 'SaaS Product',
    shortLabel: 'SaaS',
    icon: Rocket,
    color: 'indigo',
    badgeClass: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20',
    dotClass: 'bg-indigo-500',
    group: 'Product',
  },
  internal_tool: {
    key: 'internal_tool',
    label: 'Internal Software / Tool',
    shortLabel: 'Internal Tool',
    icon: Wrench,
    color: 'slate',
    badgeClass: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/20',
    dotClass: 'bg-slate-500',
    group: 'Product',
  },
  internal_product: {
    key: 'internal_product',
    label: 'Internal Product',
    shortLabel: 'Internal Product',
    icon: Wrench,
    color: 'slate',
    badgeClass: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/20',
    dotClass: 'bg-slate-500',
    group: 'Product',
  },
  content: {
    key: 'content',
    label: 'Content Creation',
    shortLabel: 'Content',
    icon: FileText,
    color: 'sky',
    badgeClass: 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20',
    dotClass: 'bg-sky-500',
    group: 'Marketing',
  },
  other: {
    key: 'other',
    label: 'Other Services',
    shortLabel: 'Other',
    icon: FolderKanban,
    color: 'zinc',
    badgeClass: 'bg-zinc-500/10 text-zinc-600 dark:text-zinc-400 border-zinc-500/20',
    dotClass: 'bg-zinc-500',
    group: 'General',
  },
};

import { getCategoryTheme, CATEGORY_THEMES } from './categoryColors';

/**
 * Returns normalized category metadata for any given category string
 */
export const getProjectCategoryMeta = (categoryKey) => {
  return getCategoryTheme(categoryKey);
};

/**
 * Clean options list for Dropdowns and Select components
 */
export const CATEGORY_OPTIONS = [
  { value: 'web_development', label: '🌐 Website / Web Development' },
  { value: 'web_design', label: '💻 Web Design / UI-UX' },
  { value: 'social_media', label: '📱 Social Media Marketing' },
  { value: 'seo', label: '🔍 Search Engine Optimization (SEO)' },
  { value: 'paid_ads', label: '🎯 Paid Ads & Performance Marketing' },
  { value: 'branding', label: '🎨 Branding & Identity' },
  { value: 'graphic_design', label: '🖌️ Graphic Design & Creatives' },
  { value: 'video_content', label: '🎬 Video Production & Content' },
  { value: 'mobile_app', label: '📲 Mobile App Development' },
  { value: 'e_commerce', label: '🛒 E-Commerce Solutions' },
  { value: 'saas_product', label: '🚀 SaaS Product / Platform' },
  { value: 'internal_tool', label: '🛠️ Internal Software / Tool' },
  { value: 'content', label: '✍️ Content Creation & Copywriting' },
  { value: 'other', label: '📁 Other Services' },
];

/**
 * Filter pills list for quick 1-click filtering
 */
export const CATEGORY_FILTER_PILLS = [
  { key: 'all', label: 'All Projects', icon: FolderKanban },
  { key: 'web_development', label: 'Website / Dev', icon: Globe },
  { key: 'web_design', label: 'Web Design', icon: Layout },
  { key: 'social_media', label: 'Social Media', icon: Share2 },
  { key: 'seo', label: 'SEO', icon: Search },
  { key: 'paid_ads', label: 'Paid Ads', icon: Target },
  { key: 'branding', label: 'Branding', icon: Sparkles },
  { key: 'graphic_design', label: 'Graphic Design', icon: Palette },
  { key: 'video_content', label: 'Video', icon: Video },
  { key: 'mobile_app', label: 'Mobile App', icon: Smartphone },
  { key: 'e_commerce', label: 'E-Commerce', icon: ShoppingBag },
  { key: 'saas_product', label: 'SaaS Product', icon: Rocket },
  { key: 'internal_tool', label: 'Internal Tool', icon: Wrench },
  { key: 'content', label: 'Content', icon: FileText },
  { key: 'other', label: 'Other', icon: FolderKanban },
];
